### PR TITLE
PEP8 code and fixed some minor bugs

### PR DESCRIPTION
**Pull request by KingAkeem**
#43

### CODE REVIEW

**Comment by PSNAppz** [comment]
@KingAkeem Check the test cases. Make sure those are passing.

**Comment by PSNAppz** [comment]
@DedSecInside/reviewers Please review.

**Comment by KingAkeem** [comment]
Thank you guys for letting me contribute. I'd like to add some more contributions, like setting up more tests, removing redundancy and refactoring code.

**Comment by agrepravin** [comment]
sounds awesome, go ahead mate @KingAkeem

**Comment by KingAkeem** [comment]
Thanks, I'm fairly new to open source and really like your project. Do you guys have a gitter?

**Comment by PSNAppz** [comment]
We use slack for communication. @KingAkeem

**Comment by KingAkeem** [comment]
I haven't received the link, could you send it to me again at akeemtlking@gmail.com?

**Comment by PSNAppz** [comment]
See this [Link](https://github.com/DedSecInside/TorBoT/invitations)

**Comment by KingAkeem** [comment]
I'm getting this error 
`Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.
`

**Comment by KingAkeem** [comment]
Trying inviting me on Slack at atking1@coastal.edu

**Comment by PSNAppz** [comment]
Ok done!

**Pull request merged**
