### PR TITLE
Dockerize torbot

### LINKED ISSUE #164: Dockerize TorBot
- Dockerize Torbot to avoid issues like #155 .
- Entry point should `torbot` binary.

### PR DESCRIPTION
**Pull request by v1shwa**
Fixes #164 

### Changes Proposed
- Add Dockerfile

### Explanation of Changes
- Ability to run torbot within a docker container.
- Updated README to add instructions to run on docker.

### CODE REVIEW

**Comment by v1shwa** [comment]
@PSNAppz Please review it & let me know if I missed something. :)

**Comment by PSNAppz** [comment]
Thank you @v1shwa for the PR. 
@KingAkeem please review and merge

**Comment by KingAkeem** [comment]
What are the instructions for testing this?

**Comment by v1shwa** [comment]
@KingAkeem I have added in the README. But, here you go, again:

- Ensure than you have a tor container running on port 9050. You can start on by running: `docker run -p 9050:9050 -d --name tor osminogin/tor-simple`

- Build docker image: `docker build -t dedsecinside/torbot .`

- Run the container (make sure to link the tor container as `tor`):
	
	`docker run --link tor:tor --rm -ti dedsecinside/torbot`

**Pull request merged**
