### PR TITLE
Feature_Save_To_File

### PR DESCRIPTION
**Pull request by y-mehta**
## Added :
             

- Save to File Feature #29

### CODE REVIEW

**Comment by PSNAppz** [comment]
@y-mehta That was fast. Great work. 👍 

Our @DedSecInside/reviewers team will review this and will merge it as soon as it is ready to merge.

**Comment by agrepravin** [comment]
@y-Mehta can u write test cases for ur module? If possible?

**Comment by y-mehta** [comment]
@agrepravin I'm sorry, but I haven't written any test cases for python till now. Still I will try to write but probably it will consume more time.

**Comment by PSNAppz** [comment]
@y-mehta Thats ok we'll write the test cases. Thank you for the PR.

**Comment by y-mehta** [comment]
Thanks @PSNAppz

**Comment by agrepravin** [comment]
No prb @y-mehta will write but good to know how to write unit tests

**Comment by PSNAppz** [comment]
@y-mehta You are added to our contributor list. 👍

**Pull request merged**
