### PR TITLE
Added feature of retreiving email_ids and web_links

### PR DESCRIPTION
**Pull request by agrepravin**
Will add few more in coming days.

### CODE REVIEW

**Comment by PSNAppz** [comment]
Great Work ! :+1: 
Thanks for the feature @agrepravin . I will merge this soon.

**Comment by agrepravin** [comment]
PR is not merged yet?

**Comment by agrepravin** [comment]
Not yet merged????

**Comment by PSNAppz** [comment]
@agrepravin No it is not merged yet.

**Comment by agrepravin** [comment]
sure

**Comment by PSNAppz** [comment]
Tested :+1:  
Need some minor modification but its good.

**Comment by agrepravin** [comment]
What are those???

**Comment by PSNAppz** [comment]
@agrepravin The output of mail is `['mailto:advertise@provaz.eu']`
you can change it to make it look beautiful like `[advertise@provaz.eu]`

**Comment by agrepravin** [comment]
Cool will do that and also start a slack channel or something for communication, what you say???

**Comment by PSNAppz** [comment]
@agrepravin Great 
I will create a slack channel and I will let you know.

**Comment by PSNAppz** [comment]
Join slack using this link [Slack Team](https://join.slack.com/dedsec-inside/shared_invite/MTk4OTY1ODA0NjkzLTE0OTc2MTIzMTQtNjgxMWU2ZTVkMw)

**Pull request merged**
