### PR TITLE
[Optimistaion] : Made the code block more efficient to understand in test_api.py file

### PR DESCRIPTION
**Pull request by Blacksujit**
# Improvements and Optimisation's  👍 

1.) updated and made the code changes in the tes_api.py file 

2.) the perform test cases are added block is added in the code

3.) feasibility of the code is improved for future perspective

### CODE REVIEW

**Comment by KingAkeem** [comment]
Could you please remove the virtual environment directory?

**Comment by Blacksujit** [comment]
ok

**Comment by Blacksujit** [comment]
> Could you please remove the virtual environment directory?

There is no venv   if so can you please point it out

**Comment by KingAkeem** [comment]
> > Could you please remove the virtual environment directory?
> 
> There is no venv if so can you please point it out

It is called `torbot_venv`

**Pull request closed without merging**
