### PR TITLE
Add .gitattributes file

### PR DESCRIPTION
**Pull request by ChaminW**
### Changes Proposed
This file will normalize the way handles the line endings as the file format.

### CODE REVIEW

**Comment by KingAkeem** [comment]
I'm sorry, I don't quite understand the use of this addition. Could you give me a brief explanation?

**Comment by ChaminW** [comment]
This pull request adds a .gitattributes file in the root of the project indicating text=auto so that Git clients will automatically convert line endings to the correct platform line endings when cloning, and normalize them back to LF when committing. Further, adding separate configurations for identified file formats to leave untouched as binary.

**Comment by PSNAppz** [comment]
@KingAkeem Please review this.

**Comment by KingAkeem** [comment]
> 
> 
> This pull request adds a .gitattributes file in the root of the project indicating text=auto so that Git clients will automatically convert line endings to the correct platform line endings when cloning, and normalize them back to LF when committing. Further, adding separate configurations for identified file formats to leave untouched as binary.

Thanks for the explanation, sounds like a great idea!

**Comment by PSNAppz** [comment]
@ChaminW Great work 👏🏻

**Pull request merged**
