### PR TITLE
A mission to produce a beautiful and comprehensible code base. (Documenting and Refactoring)

### PR DESCRIPTION
**Pull request by KingAkeem**
getweblinks.py module now uses two functions to validate urls instead of check if 'http' or 'https' exist in the url. Both functions use regular expressions to check the validity of a url, one is specially geared towards onion urls because it's what it will be used mostly for. 
Also put integers into constant variables so there's no "magic constants"

### CODE REVIEW

**Comment by PSNAppz** [comment]
@KingAkeem Let me know when this is ready to merge.

**Comment by KingAkeem** [comment]
@PSNAppz I've already finished the documentation. I also added functions that use regular expression to validate urls. I'm going to work on fixing the flag that saves information to a json file, it's not giving an error but the json file is not being produced.

**Comment by PSNAppz** [comment]
@KingAkeem Oh ok is there a test case for that flag?

**Comment by KingAkeem** [comment]
Didn't mean to reopen it but there is a test case for the save file module

**Comment by PSNAppz** [comment]
@KingAkeem Sorry I accidentally clicked comment and close

**Comment by KingAkeem** [comment]
Got you, what should the JSON file contain. It says {datatype: data}, but what kind of datatypes and data are you trying to save?

**Comment by PSNAppz** [comment]
@KingAkeem See this [PR](https://github.com/DedSecInside/TorBoT/pull/31/files)

**Comment by KingAkeem** [comment]
The -s flag is now working correctly according to the pull request, should be ready for merge.

**Comment by PSNAppz** [comment]
@KingAkeem Thank you for the PR. You did a great job. making this project a better one. Keep up the good work.

**Comment by KingAkeem** [comment]
Thanks, I really appreciate. I just enjoy programming especially Python and this project has potential to be really interesting.

**Pull request merged**
